events {}

http {

    upstream akademik_servers {

        server backend-a:3000;
        server backend-b:3000;
        server backend-c:3000;

    }

    server {

        listen 80;

        location / {

            proxy_pass http://akademik_servers;

        }

    }

}